name: "phpunit"

on:
    pull_request:
    push:
        branches:
            - main

env:
    fail-fast: true

jobs:
    phpunit:
        name: phpunit
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: ["8.1"]

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2.3.3

            - name: "Install PHP with extensions"
              uses: shivammathur/setup-php@2.7.0
              with:
                  coverage: "none"
                  extensions: intl
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2

            - name: "Set composer cache directory"
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: "Cache composer"
              uses: actions/cache@v2.1.2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('composer.lock') }}
                  restore-keys: ${{ runner.os }}-${{ matrix.php-version }}-composer-

            - name: "Composer install"
              run: composer install --no-interaction --no-progress

            - name: PHPUnit execute
              id: execute
              run: bin/phpunit
